CREATE DATABASE STAYIN;
USE STAYIN;

CREATE TABLE EMPRESA (
	idEMPRESA INT PRIMARY KEY AUTO_INCREMENT,
	RAZAO VARCHAR(100) NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    TELEFONE CHAR(15)
);

CREATE TABLE CARGO (
    idCARGO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) CONSTRAINT CHK_NOME CHECK (NOME IN ('Técnico', 'Gerente', 'Administrador'))
);

ALTER TABLE CARGO ADD CONSTRAINT CHK_NOME_CARGO CHECK (NOME IN ('Técnico', 'Gerente', 'Administrador'));
INSERT INTO CARGO (NOME) VALUES ('Técnico'), ('Gerente'), ('Administrador');

CREATE TABLE USUARIO (
    idUSUARIO INT,
    EMAIL VARCHAR(80) NOT NULL UNIQUE,
    NOME VARCHAR(80) NOT NULL,
    SENHA VARCHAR(60) NOT NULL, 
    TELEFONE VARCHAR(15),        
    fkCARGO INT NOT NULL,
    FOREIGN KEY (fkCARGO) REFERENCES CARGO(idCARGO),
    fkEMPRESA INT NOT NULL,
    PRIMARY KEY (idUSUARIO, fkEMPRESA),
    FOREIGN KEY (fkEMPRESA) REFERENCES EMPRESA(idEMPRESA)
);

ALTER TABLE USUARIO MODIFY COLUMN idUSUARIO INT auto_increment;

INSERT INTO Empresa (RAZAO, CNPJ, TELEFONE)
VALUES ('STAYIN', 'NULL', '11946414195');

INSERT INTO USUARIO (EMAIL, NOME, SENHA, TELEFONE, fkCARGO, fkEMPRESA)
VALUES 
    ('matheus.torres@sptech.school', 'MATHEUS FERRO TORRES', 'Ferro10', '11943008452', 3, 1),
    ('reynald.costa@sptech.school', 'REYNALD ALBUQUERQUE COSTA', 'Reynald20', '11951641253', 3, 1),
    ('marcela.martins@sptech.school', 'MARCELA CARNEIRO DE OLIVEIRA MARTINS', 'Marcela30', '11946414195', 3, 1),
    ('vitoria.suliman@sptech.school', 'VITÓRIA LEMES SULIMAN', 'Vitoria40', '11970647307', 3, 1),
    ('cintia.ohara@sptech.school', 'CINTIA KAORY OHARA', 'Cintia50', '11972154074', 3, 1),
    ('matheus.csilva@sptech.school', 'MATHEUS DE CASTRO SILVA', 'Castro50', '11966372620', 3, 1);